In [1]:
import torch

In [2]:
m = torch.ones(3,4)

In [39]:
a = torch.rand(4)
print(a.stride())
print(a)

(1,)
tensor([0.6156, 0.5643, 0.1073, 0.5593])


In [40]:
m + a

tensor([[1.6156, 1.5643, 1.1073, 1.5593],
        [1.6156, 1.5643, 1.1073, 1.5593],
        [1.6156, 1.5643, 1.1073, 1.5593]])

In [41]:
a.expand_as(m)

tensor([[0.6156, 0.5643, 0.1073, 0.5593],
        [0.6156, 0.5643, 0.1073, 0.5593],
        [0.6156, 0.5643, 0.1073, 0.5593]])